site_name: GenStudio
site_url: https://studio.gen.dev
repo_url: https://github.com/probcomp/genstudio
repo_name: probcomp/genstudio
edit_uri: tree/docs/docs/
theme:
  name: material
  custom_dir: docs/overrides
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil-box
    download: material/download
  palette:
    primary: white
    accent: custom
  font:
    text: Crimson Pro
  features:
    - navigation.indexes
    - toc.integrate
    - content.action.edit
  logo: false
nav:
  - Home: index.md
  - Quickstart: quickstart.py
  - System Guide:
    - Layouts: system-guide/layouts.py
    - State: system-guide/state.py
    - HTML with Hiccup: system-guide/html-with-hiccup.py
    - JS Imports: system-guide/js-imports.py
  - Interactivity & Animation:
    - Sliders: interactivity/sliders.py
    - Animating Frames: interactivity/frames.py
    - Mouse events: interactivity/events.py
    - Conditional Rendering: learn-more/cond.py
    - Tailing data: interactivity/tail.py
  - Learn More:
    - Working with Color: learn-more/color.py
    - Python Event Loops: learn-more/python-event-loop.py
    - Compare with Observable Plot: learn-more/vs-observable.py
    - Save / Export Images: learn-more/save-as-image.py
    - Plot Options: learn-more/plot-options.py
  - Examples:
      - Draw Density: examples/draw-density.py
      - Live Editing Source Code: examples/live-edit-source.py
      - Ellipse Mark: examples/ellipse-mark.py
      - Histogram Mark: examples/histogram-mark.py
      - Image Mark: examples/image-mark.py
      - Timelines with barX: examples/barx-timeline.py
      - Highlighting Code: examples/bylight.py
      - Rendering LaTeX: examples/katex.py
      - Render Pixel Data: examples/pixels.py
  - API Docs: api/plot.md
  - How Do I...: learn-more/how-do-i.py

  - Changelog: CHANGELOG.md
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
plugins:
  - search
  - genstudio.docs.plugin:
      modules:
        - module: genstudio.plot
          output: api/plot.md
  - mkdocs-jupyter:
      include: ["*.py"]
      ignore: ["llms.py"]
      execute: true
      allow_errors: false
      kernel_name: genstudio
      include_requirejs: true
      include_source: True
      remove_tag_config:
        remove_cell_tags:
          - hide
        remove_input_tags:
          - hide_source
        remove_all_outputs_tags:
          - hide_output
extra_css:
  - stylesheets/custom.css
  - stylesheets/bylight.css
extra_javascript:
  - js/bylight.js
  - js/scroll-fix.js
  - js/command-k.js
hooks:
  - src/genstudio/scripts/css_modifier.py
  - src/genstudio/scripts/tailwind_builder.py
